Add support for 'get-lease-hostnames' option for subnets
k0ste/ansible-role-isc-dhcpd pull request #3
Opened 2017-06-22 02:39 UTC by ProFfeSsoRr

2017-06-22 10:33 UTC, k0ste commented
> The _get-lease-hostnames_ statement is used to tell dhcpd whether or not to look up the domain name corresponding to the IP address of each address in the lease pool and use that address for the DHCP _hostname_ option.  If _flag_ is **true**, then this lookup is done for all addresses in the current scope.  By default, or if _flag_ is **false**, no lookups are done.

So, the value should be bool, not on/off. Also this statement must be available not only for subnet but for host, group, pool.

2017-06-23 02:50 UTC, ProFfeSsoRr commented
Fixed

2017-06-23 05:45 UTC, k0ste requested changes

2017-06-26 04:02 UTC, ProFfeSsoRr commented
Fix

2017-06-26 04:19 UTC, k0ste requested changes

2017-06-26 04:19 UTC, k0ste commented on templates/dhcpd_pool.j2
> +{{ '  get-lease-hostnames ' + p.get_lease_hostnames + ';' }}
Add a few more whitespaces to avoid breaking of format.

2017-06-26 05:50 UTC, ProFfeSsoRr commented on templates/dhcpd_pool.j2
> +{{ '  get-lease-hostnames ' + p.get_lease_hostnames + ';' }}
Ok, done

2017-06-26 09:48 UTC, k0ste approved these changes

2017-06-26 09:49 UTC, merged